/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.22
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package plplot.core;

public interface plplotjavacConstants {
  public final static String jPLFLTArray = plplotjavacJNI.get_jPLFLTArray();
  public final static String jPLFLTbracket = plplotjavacJNI.get_jPLFLTbracket();
  public final static String jPLFLTbracket2 = plplotjavacJNI.get_jPLFLTbracket2();
  public final static int PLESC_SET_RGB = plplotjavacJNI.get_PLESC_SET_RGB();
  public final static int PLESC_ALLOC_NCOL = plplotjavacJNI.get_PLESC_ALLOC_NCOL();
  public final static int PLESC_SET_LPB = plplotjavacJNI.get_PLESC_SET_LPB();
  public final static int PLESC_EXPOSE = plplotjavacJNI.get_PLESC_EXPOSE();
  public final static int PLESC_RESIZE = plplotjavacJNI.get_PLESC_RESIZE();
  public final static int PLESC_REDRAW = plplotjavacJNI.get_PLESC_REDRAW();
  public final static int PLESC_TEXT = plplotjavacJNI.get_PLESC_TEXT();
  public final static int PLESC_GRAPH = plplotjavacJNI.get_PLESC_GRAPH();
  public final static int PLESC_FILL = plplotjavacJNI.get_PLESC_FILL();
  public final static int PLESC_DI = plplotjavacJNI.get_PLESC_DI();
  public final static int PLESC_FLUSH = plplotjavacJNI.get_PLESC_FLUSH();
  public final static int PLESC_EH = plplotjavacJNI.get_PLESC_EH();
  public final static int PLESC_GETC = plplotjavacJNI.get_PLESC_GETC();
  public final static int PLESC_SWIN = plplotjavacJNI.get_PLESC_SWIN();
  public final static int PLESC_PLFLTBUFFERING = plplotjavacJNI.get_PLESC_PLFLTBUFFERING();
  public final static int PLESC_XORMOD = plplotjavacJNI.get_PLESC_XORMOD();
  public final static int PLESC_SET_COMPRESSION = plplotjavacJNI.get_PLESC_SET_COMPRESSION();
  public final static int PLESC_CLEAR = plplotjavacJNI.get_PLESC_CLEAR();
  public final static int PLESC_DASH = plplotjavacJNI.get_PLESC_DASH();
  public final static int PLESC_HAS_TEXT = plplotjavacJNI.get_PLESC_HAS_TEXT();
  public final static int PLESC_IMAGE = plplotjavacJNI.get_PLESC_IMAGE();
  public final static int PLESC_IMAGEOPS = plplotjavacJNI.get_PLESC_IMAGEOPS();
  public final static int DRAW_LINEX = plplotjavacJNI.get_DRAW_LINEX();
  public final static int DRAW_LINEY = plplotjavacJNI.get_DRAW_LINEY();
  public final static int DRAW_LINEXY = plplotjavacJNI.get_DRAW_LINEXY();
  public final static int MAG_COLOR = plplotjavacJNI.get_MAG_COLOR();
  public final static int BASE_CONT = plplotjavacJNI.get_BASE_CONT();
  public final static int TOP_CONT = plplotjavacJNI.get_TOP_CONT();
  public final static int SURF_CONT = plplotjavacJNI.get_SURF_CONT();
  public final static int DRAW_SIDES = plplotjavacJNI.get_DRAW_SIDES();
  public final static int FACETED = plplotjavacJNI.get_FACETED();
  public final static int MESH = plplotjavacJNI.get_MESH();
  public final static int PLSWIN_DEVICE = plplotjavacJNI.get_PLSWIN_DEVICE();
  public final static int PLSWIN_WORLD = plplotjavacJNI.get_PLSWIN_WORLD();
  public final static int PL_OPT_ENABLED = plplotjavacJNI.get_PL_OPT_ENABLED();
  public final static int PL_OPT_ARG = plplotjavacJNI.get_PL_OPT_ARG();
  public final static int PL_OPT_NODELETE = plplotjavacJNI.get_PL_OPT_NODELETE();
  public final static int PL_OPT_INVISIBLE = plplotjavacJNI.get_PL_OPT_INVISIBLE();
  public final static int PL_OPT_DISABLED = plplotjavacJNI.get_PL_OPT_DISABLED();
  public final static int PL_OPT_FUNC = plplotjavacJNI.get_PL_OPT_FUNC();
  public final static int PL_OPT_BOOL = plplotjavacJNI.get_PL_OPT_BOOL();
  public final static int PL_OPT_INT = plplotjavacJNI.get_PL_OPT_INT();
  public final static int PL_OPT_FLOAT = plplotjavacJNI.get_PL_OPT_FLOAT();
  public final static int PL_OPT_STRING = plplotjavacJNI.get_PL_OPT_STRING();
  public final static int PL_PARSE_PARTIAL = plplotjavacJNI.get_PL_PARSE_PARTIAL();
  public final static int PL_PARSE_FULL = plplotjavacJNI.get_PL_PARSE_FULL();
  public final static int PL_PARSE_QUIET = plplotjavacJNI.get_PL_PARSE_QUIET();
  public final static int PL_PARSE_NODELETE = plplotjavacJNI.get_PL_PARSE_NODELETE();
  public final static int PL_PARSE_SHOWALL = plplotjavacJNI.get_PL_PARSE_SHOWALL();
  public final static int PL_PARSE_OVERRIDE = plplotjavacJNI.get_PL_PARSE_OVERRIDE();
  public final static int PL_PARSE_NOPROGRAM = plplotjavacJNI.get_PL_PARSE_NOPROGRAM();
  public final static int PL_PARSE_NODASH = plplotjavacJNI.get_PL_PARSE_NODASH();
  public final static int PL_PARSE_SKIP = plplotjavacJNI.get_PL_PARSE_SKIP();
  public final static int PL_MAXKEY = plplotjavacJNI.get_PL_MAXKEY();
  public final static int PL_MAXWINDOWS = plplotjavacJNI.get_PL_MAXWINDOWS();
  public final static int PL_NOTSET = plplotjavacJNI.get_PL_NOTSET();
  public final static int PLESPLFLTBUFFERING_ENABLE = plplotjavacJNI.get_PLESPLFLTBUFFERING_ENABLE();
  public final static int PLESPLFLTBUFFERING_DISABLE = plplotjavacJNI.get_PLESPLFLTBUFFERING_DISABLE();
  public final static int PLESPLFLTBUFFERING_QUERY = plplotjavacJNI.get_PLESPLFLTBUFFERING_QUERY();
}
