#!/bin/sh
#--------------------------------*- Tcl -*------------------------------------#
# $Id: x22,v 1.1 2004/05/21 15:09:27 andrewross Exp $
#
# Maurice LeBrun
# 12/24/02
#
# A front-end to x22.tcl for running directly from the command line, locating
# pltcl via PATH.
# Handles all usual plplot command arguments.  See "pltcl -h" for info.
#-----------------------------------------------------------------------------#
#\
exec pltcl -f "$0" ${1+"$@"}

source x22.tcl

plinit
x22
plend
